# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MbsTransformDialog
                                 A QGIS plugin
 Convert NDG Coordinates to specified Coordinate Reference System
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-09
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Marvin Ike
        email                : ike@luftbilddatenbank.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

from .ndg_converter_dialog_base import Ui_MbsTransformDialogBase

class MbsTransformDialog(QtWidgets.QDialog, Ui_MbsTransformDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(MbsTransformDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
