# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_xy.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MbsTransformDialogBase(object):
    def setupUi(self, MbsTransformDialogBase):
        MbsTransformDialogBase.setObjectName("MbsTransformDialogBase")
        MbsTransformDialogBase.resize(167, 161)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        MbsTransformDialogBase.setFont(font)
        self.label = QtWidgets.QLabel(MbsTransformDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 10, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(MbsTransformDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 150, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(MbsTransformDialogBase)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(MbsTransformDialogBase)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 150, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(MbsTransformDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(47, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(MbsTransformDialogBase)
        QtCore.QMetaObject.connectSlotsByName(MbsTransformDialogBase)

    def retranslateUi(self, MbsTransformDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MbsTransformDialogBase.setWindowTitle(_translate("MbsTransformDialogBase", "Koordinaten"))
        self.label.setText(_translate("MbsTransformDialogBase", "X-Koordinate:"))
        self.label_2.setText(_translate("MbsTransformDialogBase", "Y-Koordinate:"))
        self.pushButton.setText(_translate("MbsTransformDialogBase", "OK"))

